### ISSUE TITLE
关于设置里面的版本号和Logo

### ISSUE THREAD

**Issue by GeXiaoBai** [toraidl/hyperos_port#2]
![Screenshot_2023-12-04-22-22-30-432_com android settings](https://github.com/toraidl/hyperos_port/assets/73621689/0b73cf24-59be-4333-9b7f-00e621a4232d)
问题就是图片中的问题，望解答

**Comment by toraidl** [comment]
移植的哪个机型？
logo的overlay在/mi_ext/product/overlay/
版本信息在mi_ext的build.prop里面。
挂载失败就会这样。

**Comment by toraidl** [comment]
#mi_ext文件复制到product
cp -rf build/PORTROM/images/mi_ext/product/overlay/* build/PORTROM/images/product/overlay
cp -rf build/PORTROM/images/mi_ext/product/framework/* build/PORTROM/images/product/framework
cp -rf build/PORTROM/images/mi_ext/product/etc/permissions/platform-miui-uninstall.xml build/PORTROM/images/product/etc/permissions
cat build/PORTROM/images/mi_ext/etc/build.prop >> build/PORTROM/images/product/etc/build.prop

可以在脚本中间位置添加，把mi_ext的合并到product

**Comment by GeXiaoBai** [comment]
已经修复，感谢大佬

**Comment by toraidl** [comment]
> 已经修复，感谢大佬

你是哪个手机型号 遇到这个问题的呢？

**Comment by GeXiaoBai** [comment]
K50U，还包括人脸和自动亮度有些问题，但均已修复

**Comment by toraidl** [comment]
> K50U，还包括人脸和自动亮度有些问题，但均已修复

好的， 欢迎PR。 目前我这边只测试了A-only机型。V-AB应该还是有些许问题。

**Comment by GeXiaoBai** [comment]
好的，之后会整合然后发起PR
