### ISSUE TITLE
关于相机nfc等疑问

### ISSUE THREAD

**Issue by zfdx123** [toraidl/hyperos_port#20]
我注意到代码中存在从当前仓库复制文件到移植包来解决相机和nfc无法使用的问题，在某些情况下我们是不是应该让他从底包复制这些文件而不是打包进仓库？

**Comment by toraidl** [comment]
A13的底包，nfc是无法使用的。所以只能手动修改版，或者这个最新的提交https://github.com/toraidl/hyperos_port/commit/394ed3bb27994453608e489f47e6cb9910b7ba59 ，从同框架的A14机型移植的NFC。其他机型移植的NFC没测试过。 

相机的话，HyperOS A13的底包，应该是可以直接使用的。

**Comment by zfdx123** [comment]
并且我注意到k40 super.img的分区(不区分ab)似乎只有mi_ext odm product system system_ext vendor，在代码判断中出现了
```
    super_list="vendor mi_ext odm odm_dlkm system system_dlkm vendor_dlkm product product_dlkm system_ext"
```
这是否会对普通用户造成困扰？

**Comment by zfdx123** [comment]
![image](https://github.com/toraidl/hyperos_port/assets/47835976/0758a23b-80e4-46a6-9e65-4f4d279e3824)
这是对super比分区左边是官方线刷包的super分区，右边是打包的super

**Comment by toraidl** [comment]
那就是有问题，我没测试过非小米10系列的机型。

**Comment by toraidl** [comment]
你可以手动改成 mi_ext odm product system system_ext vendor 然后打包看一下能否启动。
可能需要clone test分支，本地运行。 dev分支某个commit导致了ext不开机。我正在逐个排除。

**Comment by zfdx123** [comment]
https://github.com/toraidl/hyperos_port/blob/fa2f02f99829dbaac393313ff940378dc406696b/port.sh#L203

这段代码是否应该是for super_list ?

**Comment by toraidl** [comment]
最新的test分支，可以试试，应该是处理了这种情况。
