### ISSUE TITLE
最新脚本关于build那里有问题

### ISSUE THREAD

**Issue by shiquanshi** [toraidl/hyperos_port#24]
后面具体日期版本号就不显示 只有V816.0.24.6..dev
sdk啥的也都不对
现在脚本打包出来的包没法开机

**Comment by toraidl** [comment]
这个应该不影响开机问题，https://github.com/toraidl/hyperos_port/blob/8b1c6fe50d59a79f3aa04f2d3ec942dc41fb12a2/port.sh#L699C5-L699C135  这一行删除sheng 和shennong的判断就行。
