### ISSUE TITLE
bin中對應的處理器架構名稱不同導致程式缺失依賴文件

### ISSUE THREAD

**Issue by chengpuliang** [toraidl/hyperos_port#25]
裝置:Mac mini (M2 Pro)
系統版本:macOS 14.5

原本執行port.sh時，一直報「命令zipalign缺失」，後來發現只要把bin/Darwin/X86_64資料夾名稱改成bin/Darwin/arm64，應該是因為程式依照CPU架構選擇bin/Darwin/arm64，但Darwin的bin只有x86_64，導致找不到依賴工具的問題，這樣雖然是x86轉譯跑依賴工具，但能解決命令缺失問題。

**Comment by chengpuliang** [comment]
![Screenshot 2024-06-23 at 12 47 44 AM](https://github.com/toraidl/hyperos_port/assets/51910669/2af8b0c5-6f53-4429-a14b-528d700931bd)

左邊為原本的問題
右邊為修改成功的結果

**Comment by toraidl** [comment]
macOS系统挂了后，就没有测试过了。  只测试了Linux
