### ISSUE TITLE
幾個問題

### ISSUE THREAD

**Issue by mialikabi** [toraidl/hyperos_port#26]
1. 你有 Telegram 或 Discord?
2. 該工具是否僅限小米10使用，還是可以在其他搭載驍龍865的手機上使用?
3.如果我使用MIUI 14 Android 12作為基礎，這個工具可以運作嗎?
因為我無法將 xiaomi.eu 從 xiaomi 14 移植到帶有基礎 miui 14 a12 的 redmi k30 pro bootloop

**Comment by toraidl** [comment]
Android 12应该不行，应该需要补很多东西，特别是vendor分区。
