### ISSUE TITLE
POCO機型炸桌面

### ISSUE THREAD

**Issue by chengpuliang** [toraidl/hyperos_port#27]
裝置:POCO X3 Pro (vayu)
完成開機引導後，系統桌面無限卡死，最後修改odm/etc/[裝置代號].build.prop即odm/etc/vayu.build.prop中
`ro.product.odm.brand=POCO`
改成
`ro.product.odm.brand=Xiaomi`
即可正常啟動系統桌面

**Comment by toraidl** [comment]
只测试过基于CN（xiaomi.eu）的底包。
