### ISSUE TITLE
更新脚本之后无法开机

### ISSUE THREAD

**Issue by GeXiaoBai** [toraidl/hyperos_port#3]
更新脚本之后制作的移植包一直处于卡一(卡三分钟)-->重启-->卡一(卡三分钟)-->重启这个循环，替换底包无用
手机：Redmi K50 Ultra(diting)
Super分区形式：V A/B
底包版本1：diting 23.9.28泄露版HyperOS
底包版本1安卓版本：Android 14
底包版本2：diting 开发版 MIUI14 V14.0.23.10.25
底包版本2安卓版本：Android 13
底包版本3：diting 稳定版 MIUI14 V14.0.11.0
底包版本3安卓版本：Android 13
注：之前Logo问题开机图为diting 23.9.28泄露版HyperOS为底包制作开机截图而来在代码注释、增加、删减按照之前可开机版本而来(该版本未备份)

**Comment by GeXiaoBai** [comment]
移植包机型：小米14Pro
移植包版本1：OS1.0.25.0
移植包版本1安卓版本：Android 14
移植包版本2：OS1.0.23.11.30
移植包版本2安卓版本：Android 14
这两种版本均被替换过上述三种底包但仍无法开机

**Comment by toraidl** [comment]
什么环境打包的？ 打包日志附一下
有反馈Ubuntu打包无法开机。但全新重装后，按Readme说明，运行依次执行steup.sh可正常打包开机。你可以在虚拟机这样试试

**Comment by GeXiaoBai** [comment]
因为图方便，所以用的wsl1，稍后我会测试实体机Ubuntu22.04的测试，如果还是不行，我将导出所有日志上传以便于修改

**Comment by GeXiaoBai** [comment]
现在打包Super分区仍有问题，他不会将*dlkm*文件打包进Super分区，这是K50 Ultra必须要的分区，K50Ultra Super的分区表应为：mi_ext.img   odm.img   product.img   system.img   system_ext.img   vendor.img   vendor_dlkm.img。现阶段无法将vendor_dlkm.img打包进Super分区，已经更改port_config中“# 可能的super子分区列表”仍无效果
Super分区解包图片(缺少vendor_dlkm.img)
![image](https://github.com/toraidl/hyperos_port/assets/73621689/69c6a639-bcff-4336-9f8a-ffa243dc6380)
build/portrom/images图片
![image](https://github.com/toraidl/hyperos_port/assets/73621689/5583d869-14dc-4d9d-b468-c15c85bd7c0b)

**Comment by GeXiaoBai** [comment]
虽然打包有问题，但是确实已经进入了二屏而并非卡一

**Comment by GeXiaoBai** [comment]
电脑版本Ubuntu 22.04.3 LTS
手机：Redmi K50 Ultra(diting)
底包版本：diting 23.9.28泄露版HyperOS
底包版本安卓版本：Android 14
移植包机型：小米14Pro
移植包版本2：OS1.0.23.11.30
移植包版本2安卓版本：Android 14

**Comment by GeXiaoBai** [comment]
已开机

**Comment by toraidl** [comment]
port_config 的partition_to_port,我弃用了，** 最初的时候没有考虑到V-AB， 我对这个机型也不是很清楚。 后面就直接定死了要打的分区。 
```
blue "正在检测ROM底包" "Validating BASEROM.."
if unzip -l ${baserom} | grep -q "payload.bin"; then
    baserom_type="payload"
    super_list="vendor mi_ext odm odm_dlkm system system_dlkm vendor_dlkm product product_dlkm system_ext"
elif unzip -l ${baserom} | grep -q "br$";then
    baserom_type="br"
    super_list="vendor mi_ext odm system product system_ext"
    
else
    error "底包中未发现payload.bin以及br文件，请使用MIUI官方包后重试" "payload.bin/new.br not found, please use HyperOS official OTA zip package."
    exit
fi
```
理论应该是要打包 vendor_dlkm的

**Comment by GeXiaoBai** [comment]
好的，一会去试试

**Comment by toraidl** [comment]
现在能正常打包吗？ 打包EROFS有问题吗？

**Comment by GeXiaoBai** [comment]
已经修复，打包正常

**Comment by GeXiaoBai** [comment]
之前忘记测试了，刚刚测试完，脚本改动比较大，我目前正在尽量减少改动，尽早发起PR

**Comment by GeXiaoBai** [comment]
打包Super的日志
![image](https://github.com/toraidl/hyperos_port/assets/73621689/e7592fc4-3865-44bc-a3d6-caca98249577)

**Comment by GeXiaoBai** [comment]
因为变量“super_list”的变量未改，所以打包了system_dlkm，更改之后并无异常
