### ISSUE TITLE
setup.sh的问题

### ISSUE THREAD

**Issue by XEKZHX** [toraidl/hyperos_port#31]
在test分支里面的setup.sh文件里的14行的std应该是zstd
https://github.com/toraidl/hyperos_port/blob/9b332ae6afce47d7ea16793b9a2337772cbc78c0/setup.sh#L14

**Comment by toraidl** [comment]
额，应该是误删了。。

**Comment by toraidl** [comment]
eb0f5dc4f012072a9e16786468279e27fe7a8b54
