### ISSUE TITLE
大佬，问俩问题，感谢！

### ISSUE THREAD

**Issue by chenmo520** [toraidl/hyperos_port#33]
1.目前还支持HyperOS1.0 A14移植吗？有没有啥要注意的
2.啥时候更新webview的修复
还有电量与性能和小米设置改崩了，应该是改自定义刷新率引起的，注释掉就挺好，哈哈

**Comment by toraidl** [comment]
1 应该没问题
2 https://github.com/toraidl/hyperos_port/blob/eb0f5dc4f012072a9e16786468279e27fe7a8b54/port.sh#L500
500-520修改一下就行
检查底包有没得，有就复制到目标
没有就直接删除移植包的
3 确实
