### ISSUE TITLE
MacOS下无法检测到“zipalign”指令

### ISSUE THREAD

**Issue by tosasitill** [toraidl/hyperos_port#5]
如题 使用brew或者pip3都无法找到软件包 请问有什么解决办法吗 已安装Android Studio

**Comment by tosasitill** [comment]
<img width="777" alt="image" src="https://github.com/toraidl/hyperos_port/assets/66861785/f35dae8d-7760-49ec-9f27-24c0157835c2">

**Comment by toraidl** [comment]
find ~/Library/Android/sdk/build-tools -name "zipalign" 你看下有没呢？ 可以把这个复制到 bin/Darwin/X86_64下

**Comment by toraidl** [comment]
最新push 已添加zipalign

**Comment by tosasitill** [comment]
解决了 实测macOS还需安装以下软件包 而且vab打包需要有问题 我正在修复
'''
pip3 install busybox 
brew install gdu gnu-sed gnu-getopt grep
'''
