### ISSUE TITLE
作者大大能不能给移植时加个详细日志输出，我以为我卡住了

### ISSUE THREAD

**Issue by SherryWangTech** [toraidl/hyperos_port#6]
![image](https://github.com/toraidl/hyperos_port/assets/152904886/34a90585-b282-4cf1-ba28-a23094034fae)
不看任务管理器我还以为我卡住了，一点日志都没得，建议而已，感谢查看

**Comment by toraidl** [comment]
你用的啥系统？ 我搞个环境试试。
linux和mac系统都是有日志输出的

**Comment by toraidl** [comment]
你是直接用的root账号打包的呀？ 联系重新创建一个账号，用sudo ./port.sh
