### ISSUE TITLE
macOS下erofs打包img错误

### ISSUE THREAD

**Issue by tosasitill** [toraidl/hyperos_port#7]
<E> erofs: failed to build shared xattrs: [Error 96] No message available on STREAM
<E> erofs: 	Could not format the device : [Error 96] No message available on STREAM

打包erofs的product.img时遇到错误，打包出来是0KB的空镜像
打包ext4时正常
<img width="744" alt="image" src="https://github.com/toraidl/hyperos_port/assets/66861785/694a4d03-d65b-47f1-981b-19f02467a3db">

**Comment by toraidl** [comment]
你看下 ls -al bin/Darwin/X86-64/mkfs.erofs有没有 x权限？ 
确保是用的sudo权限运行port.sh

**Comment by tosasitill** [comment]
是sudo运行的
刚授权完x 现在正在尝试重新打包

**Comment by tosasitill** [comment]
```
[1211-23:13:01] 以[EROFS]文件系统打包[product.img]
FSPATCH by [affggh]
LICENES [Apache 2.0]
VERSION [1.0]
FsPatcher: Load origin 1841 entries
Add [product['0', '0', '0755']]
Add [product/etc/device_features/haydn.xml['0', '0', '0644']]
Add [product/etc/displayconfig/display_id_4630946736638489730.xml['0', '0', '0644']]
FsPatcher: Add 3 entries
Done!
CONTEXTPATCH by [ColdWindScholar]
VERSION [1.0]
ContextPatcher: Load origin 1842 entries
ADD [/lost+found ['u:object_r:system_file:s0']]
ADD [/product/etc/device_features/haydn.xml ['u:object_r:system_file:s0']]
ADD [/product/etc/displayconfig/display_id_4630946736638489730.xml ['u:object_r:system_file:s0']]
ContextPatcher: Add 3 entries
Done!
mkfs.erofs 1.7-gce362738
loaded 1767 fs_config entries
<E> erofs: failed to build shared xattrs: [Error 96] No message available on STREAM
<E> erofs: 	Could not format the device : [Error 96] No message available on STREAM
```
*还是错误*

这是他的权限
```
tosasitill@mac hyperos_port-main % ls -al /Users/tosasitill/Downloads/hyperos_port-main/bin/Darwin/X86_64/mkfs.erofs   
-rwxrwxrwx@ 1 tosasitill  staff  747640 12 10 16:39 /Users/tosasitill/Downloads/hyperos_port-main/bin/Darwin/X86_64/mkfs.erofs
```
而且其他分区打包是正常的 唯有product不行

**Comment by toraidl** [comment]
https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/blob/main/bin/Darwin/x86_64/mkfs.erofs
你试试替换这个呢？

或者重新编译一个 https://github.com/sekaiacg/erofs-utils

**Comment by tosasitill** [comment]
<img width="742" alt="image" src="https://github.com/toraidl/hyperos_port/assets/66861785/8df0ae9d-893b-43ea-9d44-d4bad8a694e1">
还是报错 而且mio的这个erofs还是用我的电脑环境编译的 就很奇怪 我手动创建也失败了

**Comment by toraidl** [comment]
这个就不知道咋回事了。 我这边 macOS Sonama 正常。

**Comment by tosasitill** [comment]
我估计是一些奇怪的环境冲突了 我待会重新试着配置一下

**Comment by tosasitill** [comment]
感觉没办法解决了 我去最新的erofs utils仓库提交了issue
