### ISSUE TITLE
添加macOS的setup.sh缺少部分

### ISSUE THREAD

**Issue by tosasitill** [toraidl/hyperos_port#8]
```
pip3 install busybox 
brew install gdu gnu-sed gnu-getopt grep
```

**Comment by toraidl** [comment]
this commit b170aec0445a19bead42e11cc6b8b36f0b6c7bef  fix it.
thanks

**Comment by toraidl** [comment]
this commit b170aec0445a19bead42e11cc6b8b36f0b6c7bef  fix it.
thanks
